// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef __gdtools_h__
#define __gdtools_h__

#include "gdtools_RcppExports.h"

#endif // __gdtools_h__
