// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// get_font_metrics
double get_font_metrics(CharacterVector str, int bold, int italic, CharacterVector fontface, int fontsize);
RcppExport SEXP gdtools_get_font_metrics(SEXP strSEXP, SEXP boldSEXP, SEXP italicSEXP, SEXP fontfaceSEXP, SEXP fontsizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type str(strSEXP);
    Rcpp::traits::input_parameter< int >::type bold(boldSEXP);
    Rcpp::traits::input_parameter< int >::type italic(italicSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type fontface(fontfaceSEXP);
    Rcpp::traits::input_parameter< int >::type fontsize(fontsizeSEXP);
    __result = Rcpp::wrap(get_font_metrics(str, bold, italic, fontface, fontsize));
    return __result;
END_RCPP
}
// png_to_base64
String png_to_base64(std::string filename);
RcppExport SEXP gdtools_png_to_base64(SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    __result = Rcpp::wrap(png_to_base64(filename));
    return __result;
END_RCPP
}
// raster_to_png
void raster_to_png(IntegerVector red, IntegerVector green, IntegerVector blue, IntegerVector alpha, int w, int h, double width, double height, int interpolate, std::string filename);
RcppExport SEXP gdtools_raster_to_png(SEXP redSEXP, SEXP greenSEXP, SEXP blueSEXP, SEXP alphaSEXP, SEXP wSEXP, SEXP hSEXP, SEXP widthSEXP, SEXP heightSEXP, SEXP interpolateSEXP, SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type red(redSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type green(greenSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type blue(blueSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type w(wSEXP);
    Rcpp::traits::input_parameter< int >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type width(widthSEXP);
    Rcpp::traits::input_parameter< double >::type height(heightSEXP);
    Rcpp::traits::input_parameter< int >::type interpolate(interpolateSEXP);
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    raster_to_png(red, green, blue, alpha, w, h, width, height, interpolate, filename);
    return R_NilValue;
END_RCPP
}
