# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute string extents.
#'
#' Determines the width and height of a bounding box that's big enough
#' to (just) enclose the provided text.
#'
#' @param x Character vector of of strings to measure
#' @param bold,italic Is text bold/italic?
#' @param fontname Font name
#' @param fontsize Font size
#' @param fontfile Font file
#' @examples
#' str_extents(letters)
#' str_extents("Hello World!", bold = TRUE, italic = FALSE,
#'   fontname = "sans", fontsize = 12)
#' @export
str_extents <- function(x, fontname = "sans", fontsize = 12, bold = FALSE, italic = FALSE, fontfile = "") {
    .Call('gdtools_str_extents', PACKAGE = 'gdtools', x, fontname, fontsize, bold, italic, fontfile)
}

#' Get font metrics for a string.
#'
#' @return A named numeric vector
#' @inheritParams str_extents
#' @examples
#' str_metrics("Hello World!")
#' @export
str_metrics <- function(x, fontname = "sans", fontsize = 12, bold = FALSE, italic = FALSE, fontfile = "") {
    .Call('gdtools_str_metrics', PACKAGE = 'gdtools', x, fontname, fontsize, bold, italic, fontfile)
}

str_metrics_from_file <- function(x, fontfiles, fontsize = 12, bold = FALSE, italic = FALSE, fallback = "M") {
    .Call('gdtools_str_metrics_from_file', PACKAGE = 'gdtools', x, fontfiles, fontsize, bold, italic, fallback)
}

context_create <- function() {
    .Call('gdtools_context_create', PACKAGE = 'gdtools')
}

context_set_font <- function(cc, fontname, fontsize, bold, italic, fontfile = "") {
    .Call('gdtools_context_set_font', PACKAGE = 'gdtools', cc, fontname, fontsize, bold, italic, fontfile)
}

context_extents <- function(cc, x) {
    .Call('gdtools_context_extents', PACKAGE = 'gdtools', cc, x)
}

fontfile_context_create <- function(fontfiles) {
    .Call('gdtools_fontfile_context_create', PACKAGE = 'gdtools', fontfiles)
}

fontfile_context_set_font <- function(cc, fontsize, bold, italic, fallback) {
    .Call('gdtools_fontfile_context_set_font', PACKAGE = 'gdtools', cc, fontsize, bold, italic, fallback)
}

fontfile_context_extents <- function(cc, x) {
    .Call('gdtools_fontfile_context_extents', PACKAGE = 'gdtools', cc, x)
}

font_context_create <- function(fontname_, sans_files, serif_files, mono_files) {
    .Call('gdtools_font_context_create', PACKAGE = 'gdtools', fontname_, sans_files, serif_files, mono_files)
}

font_context_set_font <- function(cc, family, fontsize, bold, italic) {
    .Call('gdtools_font_context_set_font', PACKAGE = 'gdtools', cc, family, fontsize, bold, italic)
}

font_context_extents <- function(cc, x) {
    .Call('gdtools_font_context_extents', PACKAGE = 'gdtools', cc, x)
}

font_context_fontname <- function(cc) {
    .Call('gdtools_font_context_fontname', PACKAGE = 'gdtools', cc)
}

raster_to_str <- function(raster, w, h, width, height, interpolate) {
    .Call('gdtools_raster_to_str', PACKAGE = 'gdtools', raster, w, h, width, height, interpolate)
}

raster_to_file <- function(raster_, w, h, width, height, interpolate, filename) {
    .Call('gdtools_raster_to_file', PACKAGE = 'gdtools', raster_, w, h, width, height, interpolate, filename)
}

raster_png_ <- function(raster_, w, h, width, height, interpolate, filename) {
    .Call('gdtools_raster_png_', PACKAGE = 'gdtools', raster_, w, h, width, height, interpolate, filename)
}

base64_raster_encode <- function(raster_, w, h, width, height, interpolate) {
    .Call('gdtools_base64_raster_encode', PACKAGE = 'gdtools', raster_, w, h, width, height, interpolate)
}

base64_file_encode <- function(filename) {
    .Call('gdtools_base64_file_encode', PACKAGE = 'gdtools', filename)
}

#' @title List system fonts.
#'
#' @description List system fonts details into a data.frame containing columns foundry, family,
#' file, slant and weight.
#'
#' @examples
#' sys_fonts()
#' @export
sys_fonts <- function() {
    .Call('gdtools_sys_fonts', PACKAGE = 'gdtools')
}

best_family_match <- function(font_family = "sans") {
    .Call('gdtools_best_family_match', PACKAGE = 'gdtools', font_family)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('gdtools_RcppExport_registerCCallable', PACKAGE = 'gdtools')
})
