# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute string extents.
#'
#' Determines the width and height of a bounding box that's big enough
#' to (just) enclose the provided text.
#'
#' @param str Character ector of of strings to measure
#' @param bold,italic Is text bold/italic?
#' @param fontname Font name
#' @param fontsize Font size (in pixels)
#' @examples
#' str_extents(letters)
#' str_extents("Hello World!", bold = TRUE, italic = FALSE,
#'   fontname = "Sans", fontsize = 12)
#' @export
str_extents <- function(x, fontname = "sans", fontsize = 12L, bold = FALSE, italic = FALSE) {
    .Call('gdtools_str_extents', PACKAGE = 'gdtools', x, fontname, fontsize, bold, italic)
}

#' Get font metrics for a string.
#'
#' @return A named numeric vector
#' @param str string of text
#' @inheritParams str_extents
#' @examples
#' str_metrics("Hello World!")
#' @export
str_metrics <- function(x, fontname = "sans", fontsize = 12L, bold = FALSE, italic = FALSE) {
    .Call('gdtools_str_metrics', PACKAGE = 'gdtools', x, fontname, fontsize, bold, italic)
}

png_to_base64 <- function(filename) {
    .Call('gdtools_png_to_base64', PACKAGE = 'gdtools', filename)
}

raster_to_png <- function(red, green, blue, alpha, w, h, width, height, interpolate, filename) {
    invisible(.Call('gdtools_raster_to_png', PACKAGE = 'gdtools', red, green, blue, alpha, w, h, width, height, interpolate, filename))
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('gdtools_RcppExport_registerCCallable', PACKAGE = 'gdtools')
})
